# Two workflows
# 1. 
# 	a. Lint, test and deploy on push
# 	b. Run the lint, test and build script
# 	c. Use one or three jobs (running after each other)

# 2. Action on "issues"
# 	a. output event details in the shell via echo
# 	b. Use the "issues" event & "github" context

name: build-ci
on: 
  push: 
    branches: ["main"]
  workflow_dispatch:
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
        